### PR TITLE
fix: metadata tags filter traces when clicked

### LINKED ISSUE #858: [BUG] The metadata tags on the traces panel don't filter the traces when clicked
**Describe the bug**
When viewing traces in the traces panel, clicking on a metadata tag does not filter the traces list as expected.

**To reproduce**
1. Go to the traces panel in the Langwatch web UI.
2. Locate the list of metadata tags displayed abovev the traces list.
3. Click on any metadata tag to filter traces.
4. Notice that the traces remain unchanged, rather than filtering to match the selected tag.

**Expected behavior**
Clicking on a metadata tag should filter the displayed traces to only show those that contain the selected metadata value.

**Environment**
- Component: langwatch (web UI/traces panel)
- Browser/OS: [Comet browser, MacOS]

**Additional context**
This issue makes it hard to efficiently investigate traces by metadata. There are no error messages in the console when clicking a tag.

### PR DESCRIPTION
**Pull request by drewdrewthis**
# Related Issue

- Resolve #858

### CODE REVIEW

File: langwatch/src/components/datasets/UploadCSVModal.tsx [hunk 1]
```diff
@@ -366,7 +375,7 @@ export function CSVReaderComponent({
               Remove={Remove}
               ProgressBar={ProgressBar}
             />
-            {children ? children(acceptedFile) : null}
+            {children ? children(acceptedFile !== null) : null}
```
Comment (llmsommelier) [inline langwatch/src/components/datasets/UploadCSVModal.tsx]: wut? acceptedFile is of `File` type, but by doing `!== null` you are now passing a boolean to the children right? this will probably break stuff, or am I misunderstanding the code here?

Comment (drewdrewthis) [reply langwatch/src/components/datasets/UploadCSVModal.tsx]: You're right to question this - the naming is confusing, but the code is actually correct. Here's what's happening:
The children prop is a render prop typed as (acceptedFile: boolean) => React.ReactNode. It's not receiving the File object - it's receiving a boolean indicating whether a file exists.

The renderMapping function expects a boolean parameter (despite the misleading name acceptedFile), and the component correctly passes acceptedFile !== null which evaluates to true/false.

Comment (drewdrewthis) [reply langwatch/src/components/datasets/UploadCSVModal.tsx]: @rogeriochaves

**Comment by drewdrewthis** [comment]
@rogeriochaves this seems to work and work well. There're some tests, but feel free to confirm before approving

File: langwatch/src/hooks/useDrawer.ts [hunk 2]
```diff
@@ -1,23 +1,61 @@
...
+  | "addOrEditDataset"
+  | "editTriggerFilter"
+  | "seriesFilters";
+
+/** Generic callback type for drawer props - callers must narrow before use */
+type DrawerCallback = (...args: unknown[]) => void;
 
 // workaround to pass complexProps to drawers
-let complexProps = {} as Record<string, (...args: any[]) => void>;
+let complexProps = {} as Record<string, DrawerCallback>;
```
Comment (0xdeafcafe) [inline langwatch/src/hooks/useDrawer.ts:27]: is this safe? does it not get shared across globally? i assume we can only have 1 draw open at a time?

File: langwatch/src/components/traces/Summary.tsx [hunk 3]
```diff
@@ -106,24 +112,34 @@ const TraceSummaryValues = React.forwardRef<HTMLDivElement, { trace: Trace }>(
...
+          ([key]) =>
+            !Object.values(availableFilters).some((f) =>
+              key.startsWith(f.urlKey),
+            ) && key !== "query",
+        ),
+      );
+
+      void router.push(
+        "?" +
+          qs.stringify(
```
Comment (0xdeafcafe) [inline langwatch/src/components/traces/Summary.tsx:136]: can use `URLSearchParams` which is web native

File: langwatch/src/hooks/useDrawer.ts (hunk 2 above)
Comment (drewdrewthis) [reply langwatch/src/hooks/useDrawer.ts:27]: @0xdeafcafe I think this was just an attempt to avoid `any` -- also, I think we can have nested drawers

Comment (0xdeafcafe) [reply langwatch/src/hooks/useDrawer.ts:27]: @drewdrewthis right? i thought we can. this feels jannnk

Comment (0xdeafcafe) [reply langwatch/src/hooks/useDrawer.ts:27]: can we use context? don't need to in this pr, but we should deal with it imo.

File: langwatch/src/components/traces/Summary.tsx (hunk 3 above)
Comment (drewdrewthis) [reply langwatch/src/components/traces/Summary.tsx:136]: @0xdeafcafe the qs uses more advanced features that aren't supported by the `URLSearchParams` i think
