### PR TITLE
fix: exclude real_time experiments from license experiment count

### LINKED ISSUE #2568: Evaluations list page hides experiments that still count against license limits
## Describe the bug

The Evaluations list page shows fewer experiments than actually exist in the database, but the license enforcement system counts **all** experiments (including hidden ones) against the plan limit.

In one observed case:
- Database contains 7 experiments (6 `BATCH_EVALUATION_V2` + 1 `EVALUATIONS_V3`)
- Evaluations list page shows only 2
- License enforcement counts all 7 against the free plan limit of 3
- User cannot create new experiments and receives no explanation

The hidden experiments appear to be:
- Old test/SDK-created experiments without associated workflow runs
- Experiments created by integration tests or SDK usage that have no visible runs in the evaluations list query

## To reproduce

1. Create experiments via SDK or integration tests (they accumulate in the DB)
2. Go to the Evaluations list page — only experiments with visible runs appear
3. Try to run an evaluation from Studio — fails with 403 (license limit exceeded)
4. User sees 2 experiments in the UI but is told they've hit the limit

## Expected behavior

Either:
- **Option A**: The evaluations list should show ALL experiments that count against the license limit, so users can see what's using their quota and delete unused ones
- **Option B**: The license enforcement should only count experiments that are visible/active (matching the same filter criteria as the list page)
- **Option C**: Provide a way for users to see and manage their experiment quota (e.g., a usage/limits page showing "7/3 experiments used" with ability to delete old ones)

## Key files

- `langwatch/src/server/api/routers/experiments.ts` — `getAllForEvaluationsList` filters experiments (e.g., excludes `real_time` type)
- `langwatch/src/server/license-enforcement/license-enforcement.repository.ts` — `getExperimentCount` counts ALL experiments with no filter
- `langwatch/src/pages/[project]/evaluations.tsx` — evaluations list page

## Additional context

The `getAllForEvaluationsList` query filters out experiments where `workbenchState.task === "real_time"`, and the list page only shows experiments that have runs with data. But `getExperimentCount` in the license enforcement repo does a raw `prisma.experiment.count()` with no filters beyond `projectId`.

### PR DESCRIPTION
**Pull request by sergioestebance**
## Summary

Fixes #2568

- `getExperimentCount` in the license enforcement repository now excludes experiments where `workbenchState.task === "real_time"`
- These real-time experiments are online evaluations already counted under `maxOnlineEvaluations` via the `Monitor` table
- Previously they were double-counted (once as experiment, once as monitor) while being hidden from the evaluations list UI
- Uses `findMany` + JS filter (same approach as `getAllForEvaluationsList`) since Prisma JSON path filtering is unreliable for nested fields

## Test plan

- [x] Added 7 unit tests for `getExperimentCount` covering:
  - Excludes real_time experiments
  - Counts experiments with null/non-object workbenchState
  - Returns zero when all experiments are real_time
  - Returns zero when no experiments or projects exist
- [x] All 164 license-enforcement unit tests pass
- [x] Typecheck passes (pre-existing generated type errors only)

# Related Issue

- Resolve #2568

### CODE REVIEW

File: langwatch/src/server/license-enforcement/license-enforcement.repository.ts [hunk 1]
```diff
@@ -403,6 +405,12 @@ export class LicenseEnforcementRepository
     return this.prisma.experiment.count({
       where: {
         projectId: { in: projectIds },
+        NOT: {
+          workbenchState: {
+            path: ["task"],
+            equals: "real_time",
+          },
+        },
```
Comment (rogeriochaves) [inline langwatch/src/server/license-enforcement/license-enforcement.repository.ts:413]: hmmm those are legacy evaluators, shouldn't be a problem for any customers going forward, but it's ok
