### PR TITLE
fix(billing): prevent cancellation invoice from reactivating subscription

### LINKED ISSUE #2864: Subscription cancellation triggers incorrect seat allocation, wrong Slack notification, and no access revocation
## Describe the bug

When a user cancels their subscription via Stripe, three incorrect behaviors occur simultaneously:

### 1. 20 seats allocated on cancellation
Upon cancellation, the system immediately provisions 20 seats on the Growth plan (shown as "Members / Seats: 1/20" in the billing page). The organization previously had fewer seats.

### 2. Slack notification says "Subscription activated" instead of cancelled
The internal Slack webhook fires a **"Subscription activated"** message (e.g., "Org is live on GROWTH_SEAT_USD_MONTHLY") at the exact time of cancellation. The notification should either say "Subscription cancelled" or not fire at all.

### 3. User retains full platform access after cancellation
After cancellation, the user can still access all platform features. The billing page still shows the Growth plan as "Current" with full feature access. Stripe shows the subscription as "Cancelled" with "No future invoices", but the platform does not reflect this.

---

### 20 seats: hardcoded fallback in plan limits

The number 20 comes from `langwatch/ee/billing/planLimits.ts:163-176` — all Growth Seat plans define `maxMembers: 20` as their default in `PLAN_LIMITS`.

The bug chain:

1. **On cancellation**, `subscription.repository.ts` `cancel()` nullifies all numeric override fields including `maxMembers`:
   ```typescript
   ...Object.fromEntries(
     NUMERIC_OVERRIDE_FIELDS.map((f) => [f, null]),
   ),
   ```

2. **When the UI queries the plan**, `planProvider.ts` `getActivePlan()` checks if the DB has a `maxMembers` value. Since it's now `null`, it **falls back to `PLAN_LIMITS`** for the plan type — which returns **20** for Growth Seat plans.

3. **The subscription status isn't checked properly** — a cancelled subscription with a Growth Seat plan type still resolves to the full Growth plan limits instead of falling back to the free tier.

### "Subscription activated" Slack message

In `webhookService.ts:434-443`, the `activate()` path fires a Slack notification with `type: "confirmed"`. The Stripe `invoice.payment_succeeded` webhook fires even during the cancellation flow (a $0.00 invoice is generated on cancellation), which triggers the activation path instead of being recognized as a cancellation-related event.

### Access retained after cancellation

`getActivePlan()` in `planProvider.ts` does not properly gate on subscription status. A cancelled subscription with a Growth Seat plan type still resolves to full Growth plan limits.

---

## Key Files

| Bug | Root cause | File |
|-----|-----------|------|
| 20 seats on cancel | `cancel()` nullifies `maxMembers`, plan provider falls back to hardcoded 20 | `subscription.repository.ts`, `planProvider.ts` |
| "Activated" Slack msg | $0 invoice on cancellation triggers `invoice.payment_succeeded` → `activate()` path | `webhookService.ts` |
| Access retained | `getActivePlan()` doesn't check subscription status properly | `planProvider.ts` |

## To reproduce

1. Have an active Growth Seat plan subscription
2. Cancel the subscription through Stripe (or via "Manage Subscription" portal)
3. Observe: billing page shows Growth plan with 20 seats, Slack shows "activated", and user retains access

## Expected behavior

1. Seat count should not increase on cancellation — it should remain unchanged until the billing period ends, then drop to the free tier
2. Slack notification should say "Subscription cancelled" (or not fire)
3. After the billing period ends, the user should be downgraded to the free tier with appropriate access restrictions

### PR DESCRIPTION
**Pull request by sergioestebance**
## Summary

Fixes #2864

When a user cancels their subscription, Stripe generates a $0 invoice which triggers `invoice.payment_succeeded`. This caused the webhook handler to **reactivate** the cancelled subscription, leading to multiple symptoms. Additionally, the billing page hid invoices after cancellation and no Slack notification was sent for cancellations.

### Bugs fixed

| # | Bug | Root cause | Fix |
|---|-----|-----------|-----|
| 1 | **20 seats allocated on cancellation** | $0 invoice reactivated the subscription, resolving to Growth Seat defaults (maxMembers: 20) | Guard clause checks Stripe subscription status before activating |
| 2 | **"Subscription activated" Slack notification** | The activate() path fires a "confirmed" Slack message from the $0 invoice | Guard prevents activation; added new "cancelled" notification type sent from `handleSubscriptionDeleted()` |
| 3 | **User retains platform access** | Subscription was set back to ACTIVE by the $0 invoice | Same guard prevents reactivation |
| 4 | **Invoices hidden after cancellation** | `InvoicesBlock` only rendered when `hasStripeSubscription` was truthy (null after cancellation) | Always render `InvoicesBlock` — it handles empty state internally |

### Key changes

**Webhook guard** (`webhookService.ts`):
- `syncInvoicePaymentSuccess()` now checks Stripe subscription status before activating
- Wrapped in try/catch with fail-open semantics (won't break normal renewals if Stripe is unreachable)

**Cancellation Slack notification** (`types.ts`, `notification.service.ts`, `webhookService.ts`):
- Added `"cancelled"` notification type to `SubscriptionNotificationPayload`
- `buildCancelledBlocks()` sends "Subscription cancelled" header with org name, plan, and cancellation date
- `handleSubscriptionDeleted()` now dispatches the cancelled notification

**Invoice visibility** (`SubscriptionPage.tsx`):
- `InvoicesBlock` is always rendered (previously gated on active subscription)
- Component already handles empty state when there are no invoices

## Test plan

- [x] Cancelled Stripe subscription skips activation (3 regression tests)
- [x] Stripe API failure proceeds with activation — fail-open (1 test)
- [x] Active Stripe subscription activates normally — no regression (1 test)
- [x] Cancelled subscription returns free tier limits (1 test)
- [x] `handleSubscriptionDeleted` sends "cancelled" Slack notification (3 tests)
- [x] Notification service builds correct "cancelled" blocks (3 tests)
- [x] InvoicesBlock visible after cancellation (1 integration test)
- [x] 97 total tests passing

### CODE REVIEW

File: langwatch/ee/billing/services/webhookService.ts [hunk 1]
```diff
@@ -254,6 +254,26 @@ export class EEWebhookService implements WebhookService {
 
     await this.subscriptionRepository.cancel({ id: existingSubscription.id });
 
+    // Send "Subscription cancelled" Slack notification
+    try {
+      const org = await this.organizationRepository.findNameById(
```
Comment (0xdeafcafe) [inline langwatch/ee/billing/services/webhookService.ts:259]: just a note, that a repo should only be used by it's owner. so org used org repo, sub uses sub repo.

webhook can use org and sub service, etc.

don't have to change in this pr as pretty out of scope, just fyi

**Review by 0xdeafcafe — APPROVED** [review]
