### PR TITLE
fix(studio): merge localPromptConfig into parameters on workflow save

### LINKED ISSUE #3437: Workflow evaluator returns different results when run on traces vs evaluations workflow
## Problem

The same evaluator (a workflow-type evaluator) produces different results depending on whether it is triggered from a **trace run** (via monitor) or from the **workflow editor**, even when evaluating the same question.

- **On trace run:** the evaluator **always fails**
- **On workflow editor run:** the evaluator **passes**

## Root Cause (Confirmed)

**When a user edits a Prompt node's system prompt in the workflow editor UI and publishes, the new prompt is NOT saved to `parameters` in the published `WorkflowVersion` DSL.** The backend execution path (`execute_flow` → `llm.py.jinja`) reads only `parameters.instructions` and `parameters.messages` — so the LLM receives the OLD/default prompt instead of the user's configured evaluation prompt.

### Evidence

**Customer's workflow** (`workflow__0fULydyVwce98cfFhjVB`):
- `parameters.instructions` = `"You are a helpful assistant."` (default)
- `parameters.messages` = `[{"role": "user", "content": "{{input}}"}]`
- `localPromptConfig.messages` = Full evaluation prompt with entity matching rules, `{{fetch_report_code_input}}`, `{{classifier_output}}`, `{{input}}`
- Backend uses `parameters` → LLM gets generic prompt → tries to answer user's question → always fails

**Reproduced locally** (`workflow_z9nIwGSrgrTBb2aXG5Z9H`):
- Created workflow as bias evaluator, then edited prompt to entity matching evaluator
- `parameters.instructions` = Old cognitive bias evaluation prompt (from initial creation)
- `parameters.messages` = `[{"role":"user","content":"Response to be evaluated:\n\n{{llm_output}}"}]` (old template variables)
- `localPromptConfig` = `null`
- The new entity matching prompt is **nowhere in the published version**
- Backend uses `parameters` → LLM gets old bias prompt → outputs "can't assess whether it contains cognitive biases" → always fails

### How the backend reads the prompt

`langwatch_nlp/studio/templates/llm.py.jinja` (lines 22-31):
```jinja
{% if parameters.get('instructions', '') %}
{{ escape_prompt(parameters.get('instructions', '')) }}
{% endif %}
{% if parameters.get('messages', '') %}
_messages = [
    {% for message in parameters.get('messages', []) %}
    {"role": "{{ message.role }}", "content": {{ escape_prompt(message.content) }}},
    {% endfor %}
]
{% endif %}
```

Only `parameters` is read. `localPromptConfig` is never consulted during execution.

### How the UI saves the prompt

The workflow editor UI updates `localPromptConfig` (or an in-memory state) when the user edits a prompt, but this is NOT synced back to `parameters` when the workflow version is saved/published. The `parameters` array retains whatever was set at node creation time.

## Reproduction Steps

1. Create a new workflow with a Prompt/Signature node (any prompt)
2. Publish it
3. Edit the Prompt node's system prompt to something different
4. Publish again
5. Check the published `WorkflowVersion` DSL — `parameters.instructions` still has the OLD prompt
6. Set up a monitor using this workflow evaluator
7. Send traces → evaluator always fails with the old prompt's behavior

## Fix Direction

The prompt editing flow needs to sync `localPromptConfig` (or the UI's prompt state) back into `parameters.instructions` and `parameters.messages` before saving/publishing the workflow version.

## Key Code Paths

- Prompt template: `langwatch_nlp/studio/templates/llm.py.jinja:22-31`
- Signature parser: `langwatch_nlp/studio/parser.py` → `parse_component` case "signature"
- Workflow save/publish: needs investigation — where does the UI serialize `localPromptConfig` vs `parameters`?

## Affected Workflows

- Customer: `workflow__0fULydyVwce98cfFhjVB` (project `celeste-prod-FzsKx-`)
- Reproduction: `workflow_z9nIwGSrgrTBb2aXG5Z9H` (project `testlangwatchai-M_h0Mz`)

### PR DESCRIPTION
**Pull request by sergioestebance**
## Why

Closes #3437

Workflow evaluators using Prompt (signature) nodes always failed when triggered from trace monitors, even though they worked correctly in the workflow editor. A customer reported that their "classifier relevance" evaluator consistently failed on traces with generic LLM responses ("I don't have access to the data...") while passing when run from the editor.

## What changed

Call `mergeLocalConfigsIntoDsl()` in `saveOrCommitWorkflowVersion()` before persisting the DSL. This function already existed and was called by all 5 editor execution hooks, but was never called on save — so `parameters` (read by the backend) stayed stale while `localPromptConfig` (used by the editor) had the correct prompt.

The fix is a single call site in `saveOrCommitWorkflowVersion`, which is the chokepoint for all 10 workflow save paths (workflows, experiments, evaluators, agents).

## How it works

The workflow editor stores prompt edits in `localPromptConfig` on the node data. The backend (`llm.py.jinja`) reads `parameters.instructions` and `parameters.messages` to build the LLM prompt. These two were never synced on save:

- **Before**: `localPromptConfig` saved as-is, `parameters` retained creation-time values → backend used stale prompt
- **After**: `mergeLocalConfigsIntoDsl()` runs on save → extracts system message into `parameters.instructions`, non-system messages into `parameters.messages`, strips `localPromptConfig` → backend gets the correct prompt

## Test plan

- **Integration test**: `workflows.saveOrCommit.integration.test.ts` — verifies `localPromptConfig` is merged into `parameters` in the persisted DSL, and that nodes without `localPromptConfig` pass through unchanged
- **Manual E2E reproduction**: Created a workflow evaluator with a Code → Prompt pipeline, set up a monitor with span-level trace mappings, sent multi-span traces via populator. Before fix: evaluator always failed with stale prompt. After fix: evaluator passes with correct entity matching
- **Existing unit tests**: All 16 `mergeLocalConfigs.unit.test.ts` tests pass (the merge logic itself is unchanged)

## Anything surprising?

- Existing broken workflows require one re-save + re-publish cycle. The correct prompt is already in `localPromptConfig` in the current version — the fix syncs it to `parameters` on the next save. No data migration needed.
- The `as any` casts on the merge call are forced by `z.array(z.any())` in the workflow Zod schema. Tracked as a follow-up to tighten the schema boundary.

### CODE REVIEW

File: langwatch/src/server/api/routers/workflows.ts [hunk 1]
```diff
@@ -1287,12 +1288,12 @@ export const saveOrCommitWorkflowVersion = async ({
...
 
-  const dslWithoutStates = JSON.parse(
-    JSON.stringify({
-      ...input.dsl,
-      state: {},
-    }),
-  );
+  const dslWithMergedConfigs = {
+    ...input.dsl,
+    nodes: mergeLocalConfigsIntoDsl(input.dsl.nodes as any) as any,
```
Comment (drewdrewthis) [inline langwatch/src/server/api/routers/workflows.ts:1297]: Double `as any` — `as any` on both the input and output of `mergeLocalConfigsIntoDsl`. Usually a sign the function's exported types don't line up with the caller's. Worth confirming that `mergeLocalConfigsIntoDsl` accepts `typeof input.dsl.nodes` directly; if so, drop both casts. If the types genuinely diverge, add a tight comment explaining why the cast is needed.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+        slug: `test-team-${nanoid(6)}`,
+        name: "Test Team",
+        organizationId: `test_org_${nanoid(8)}`,
+        members: { create: { userId, role: "ADMIN" } },
+      },
+    });
+    await prisma.project.create({
+      data: {
+        id: projectId,
+        name: "Test Project",
```
Comment (drewdrewthis) [inline langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: `organizationId: \`test_org_${nanoid(8)}\`` creates a team referencing an Organization row that was never inserted. If the schema has a FK constraint on `teams.organizationId`, this will throw on `prisma.team.create` — the test is passing only if FK isn't enforced (either schema-level or disabled in the test environment). Safer: create the Organization in `beforeAll` too, or skip the orgId link if the schema allows it.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts [hunk 3]
```diff
@@ -0,0 +1,239 @@
...
+      expect(instructions?.value).not.toContain("helpful assistant");
+
+      // Messages must reference the evaluation inputs
+      expect(messages?.value).toEqual([
+        { role: "user", content: "{{input}}" },
+      ]);
+
+      // localPromptConfig must be stripped
+      expect(signatureNode.data.localPromptConfig).toBeUndefined();
+
```
Comment (drewdrewthis) [inline langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts:114]: The localPromptConfig has 2 messages (system + user) but this asserts `messages.value` has only the user one — implying `mergeLocalConfigsIntoDsl` splits the system message out (presumably into `instructions.value`). That's subtle behavior; a short comment here (`// system message goes to instructions, remaining messages go to messages.value`) would save the next reader a round-trip through the merge function.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts [hunk 4]
```diff
@@ -0,0 +1,239 @@
...
+      },
+    });
+  });
+
+  afterAll(async () => {
+    await prisma.workflowVersion.deleteMany({ where: { projectId } });
+    await prisma.workflow.deleteMany({ where: { projectId } });
+    await prisma.project.deleteMany({ where: { id: projectId } });
+    await prisma.team.deleteMany({ where: { id: teamId } });
+    await prisma.user.deleteMany({ where: { id: userId } });
```
Comment (drewdrewthis) [inline langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: Missing coverage I'd add before merge: (a) localPromptConfig with NO inputs/outputs override — does merge preserve existing? (b) multiple signature nodes in the same DSL — does the map handle all of them? (c) non-signature nodes — do they pass through untouched? The current two tests cover the happy path; the regressions most likely to land later are in these branches.

**Review by drewdrewthis — COMMENTED** [review]
Fix is surgical and targets the right chokepoint. Three concerns inline (type casts, test setup fragility, messages-merge assertion), plus a flag: the PR has 3 CI failures that aren't explained in the description — worth a line on whether they're pre-existing or this PR's.

File: langwatch/src/server/api/routers/workflows.ts (hunk 1 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/workflows.ts:1297]: Valid — the types genuinely diverge at the Zod boundary. `input.dsl.nodes` is `z.array(z.any())` (dsl.ts:295) while `mergeLocalConfigsIntoDsl` expects `Node<Component>[]`. Added a comment explaining the cast in d89952240.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts (hunk 2 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: Good catch — this is safe because the project uses `relationMode = "prisma"` (no FK constraints at DB level, integrity is ORM-enforced). Added a comment clarifying this in d89952240.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts (hunk 3 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts:114]: Agreed, added a clarifying comment: "mergeLocalConfigsIntoDsl splits the system message into instructions and keeps only non-system messages in the messages parameter." Fixed in d89952240.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts (hunk 4 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: Cases (b) multiple signature nodes and (c) non-signature passthrough are already covered by the 16 existing unit tests in `mergeLocalConfigs.unit.test.ts` — specifically the "when nodes include a mix of types" describe block. This integration test proves the wiring (that merge is called on save), not the merge logic itself. For (a), `LocalPromptConfig` always requires `inputs` and `outputs` fields, so the "no override" case can't happen at the type level.

Comment (drewdrewthis) [reply langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: Agreed on function-level coverage — 16 unit tests on the merge fn is solid. The residual question is integration-level: does the save path invoke merge correctly for DSLs containing *multiple* signature nodes and mixed node types together? If the existing signature-node test indirectly proves that (merge runs, non-signature nodes pass through), we're fine. If not, one more integration case would lock it in. Your call whether that's worth the cost.

**Comment by drewdrewthis** [comment]
One last thing before merge: CI shows 3 failures on this PR — `test-integration (1)`, `test-integration (4)`, `langwatch-app-complete`. Look like recurring infra-level fails rather than this PR's code, but worth a one-liner confirming they're pre-existing / unrelated to the diff. Otherwise this looks ready.

**Comment by drewdrewthis** [comment]
Tech-debt followup (not blocking):

The `JSON.parse(JSON.stringify(dslWithMergedConfigs))` at line 1296 is a belt-and-suspenders deep-clone. If `mergeLocalConfigsIntoDsl` already returns a fresh object (doesn't mutate input), the stringify dance is redundant and costs unnecessary CPU on large DSLs. Worth a one-liner check + trim in a follow-up.

File: langwatch/src/server/api/routers/workflows.ts (hunk 1 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/workflows.ts:1297]: Can't use `clearDsl()` directly — it strips `version` and `workflow_id` which are needed for persistence (it's designed for diff comparison, not save). The per-node `execution_state` concern is valid but **pre-existing** — the original code also used `JSON.parse(JSON.stringify({ ...input.dsl, state: {} }))` without stripping per-node `execution_state`. Our change doesn't introduce or worsen this. Filed as a follow-up concern but out of scope for this bug fix.

File: langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts (hunk 4 above)
Comment (sergioestebance) [reply langwatch/src/server/api/routers/__tests__/workflows.saveOrCommit.integration.test.ts]: Agreed — the existing test DSL already has an `entry` node (non-signature) alongside the `llm_call` (signature), so the mixed-type passthrough is implicitly covered. The merge runs on the full nodes array, so if entry passes through unchanged and signature gets merged, we've proven the map handles both. Not worth the extra test cost for this wiring-level assertion.

**Review by drewdrewthis — APPROVED** [review]
Approving on Drew's behalf. Earlier review comments were addressed or tech-debt non-blockers. CI green, MERGEABLE.
