### PR TITLE
fix(typescript-sdk): preserve object data in createSafeFallbackValue …

### LINKED ISSUE #906: Fix createSafeFallbackValue to preserve object data via JSON serialization
## Summary
Fixed `createSafeFallbackValue` in typescript-sdk to return JSON-stringified objects instead of losing data with `[object]`.

## Changes
- Objects are now JSON stringified, preserving data for debugging/observability
- Circular references gracefully fallback to `{"type":"raw","value":"[Non-Serializable]"}`
- Updated tests to match correct behavior
- Added explicit test for circular reference handling

## Files Changed
- `typescript-sdk/src/observability-sdk/span/input-output.ts`
- `typescript-sdk/src/observability-sdk/span/__tests__/input-output.test.ts`

## Impact
Minor - improves data preservation in span input/output processing

### PR DESCRIPTION
**Pull request by drewdrewthis**
…via JSON serialization

- JSON stringify objects instead of returning '[object]'
- Circular refs fallback to {type:'raw',value:'[Non-Serializable]'}
- Update tests to expect JSON output
- Add test for circular reference handling

Closes #906

# Related Issue

- Resolve #906

### CODE REVIEW

File: typescript-sdk/src/observability-sdk/span/input-output.ts [hunk 1]
```diff
@@ -21,8 +21,13 @@ const simpleChatMessageArraySchema = z.array(simpleChatMessageSchema);
  */
 function createSafeFallbackValue(value: unknown): string {
   if (typeof value === 'object' && value !== null) {
-    return `[${typeof value}]`;
+    try {
+      return JSON.stringify(value);
+    } catch {
+      return JSON.stringify({ type: "raw", value: "[Non-Serializable]" });
```
Comment (rogeriochaves) [inline typescript-sdk/src/observability-sdk/span/input-output.ts:27]: hmmm I think we can be smarter than this here, but this is already much better than before 🚢
